name: ci-deny-merge

on: 
  pull_request

jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Análisis de código
          run: echo 'Realizando análisis de SAST'
        -
          name: Checkout repository
          uses: actions/checkout@v3
        - 
          name: Buscar archivo en repositorio
          uses: jeertmans/filesfinder@latest
          id: allow_pull
          with:
            args: "allow_pull_request.txt"
        - 
          name: Valor a variable
          run: echo "GITHUB_ALLOWED=$(echo ${{ steps.allow_pull.outputs.files == 'allow_pull_request.txt' }})" >> $GITHUB_ENV
          # run: echo ${{ steps.allow_pull.outputs.files == 'allow_pull_request.txt' }}
        -
          name: Archivo existe
          if: ${{ env.GITHUB_ALLOWED == 'true' }}
          run: echo 'Permitiendo Pull Request'
        -
          name: Archivo no existe
          if: ${{ env.GITHUB_ALLOWED == 'false' }}
          run: echo 'Build fallida. Impidiendo Pull Request' && exit 1  